FROM camptocamp/mapfish_print:4.0.6@sha256:eef695b03d4b3d194fa4cd013259f559257aaa45066c8664d9dbd3de921b802b

ENV JAVA_OPTS="-Dfile.encoding=UTF-8 -Duser.timezone=UTC -Xmx512M"

CMD [ "catalina.sh", "run" ]
