name: Build latest release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v5

      - name: Setup Node.js 🧮
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache Node.js modules 💾
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        run: npm ci

      - name: Build artifacts 🏗️
        run: npm run build

      - name: Build docs 📔
        run: npm run build:docs

      - name: Get the version 📎
        run: |
          echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Deploy docs (latest) 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/docs
          target-folder: latest

      - name: Release 🚀
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Generate coverage 🧪
        run: npm test

      - name: Run SonarQube analysis 🔍
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
